# Department Top Three Salaries
#### A company's executives are interested in seeing who earns the most money in each of the company's departments. A high earner in a department is an employee who has a salary in the top three unique salaries for that department.

#### Write a solution to find the employees who are high earners in each of the departments.

#### Return the result table in any order.

In [1]:
import pandas as pd

In [27]:
# Step 1: Load the data into pandas DataFrames
employee_data = {
    'id': [1, 2, 3, 4, 5, 6, 7],
    'name': ['Joe', 'Henry', 'Sam', 'Max', 'Janet', 'Randy', 'Will'],
    'salary': [85000, 80000, 60000, 90000, 69000, 85000, 70000],
    'departmentId': [1, 2, 2, 1, 1, 2, 1]
}

department_data = {
    'id': [1, 2],
    'name': ['IT', 'Sales']
}

employee_df = pd.DataFrame(employee_data)
department_df = pd.DataFrame(department_data)
print(employee_df)
print("\n")
print(department_df)

   id   name  salary  departmentId
0   1    Joe   85000             1
1   2  Henry   80000             2
2   3    Sam   60000             2
3   4    Max   90000             1
4   5  Janet   69000             1
5   6  Randy   85000             2
6   7   Will   70000             1


   id   name
0   1     IT
1   2  Sales

In [31]:
def top_three_salaries(employee: pd.DataFrame, department: pd.DataFrame) -> pd.DataFrame:
    # Get top three unique salaries per department
    top_salaries_df = employee.groupby('departmentId').apply(lambda x: x.nlargest(3, 'salary')).reset_index(drop=True)

    # Merge with department names
    result_df = top_salaries_df.merge(department, left_on='departmentId', right_on='id', how='left')

    # Select required columns
    result_df = result_df[['name_y', 'name_x', 'salary']]
    result_df.columns = ['Department', 'Employee', 'Salary']
    return result_df

top_three_salaries(employee_df, department_df)

<ipython-input-31-c7721a82266e>:3: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  top_salaries_df = employee.groupby('departmentId').apply(lambda x: x.nlargest(3, 'salary')).reset_index(drop=True)

  Department Employee  Salary
0         IT      Max   90000
1         IT      Joe   85000
2         IT     Will   70000
3      Sales    Randy   85000
4      Sales    Henry   80000
5      Sales      Sam   60000